#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ ! -d $OPENSHIFT_DATA_DIR/runtime ]; then
    mkdir $OPENSHIFT_DATA_DIR/runtime
fi

ln -sf $OPENSHIFT_DATA_DIR/runtime $OPENSHIFT_REPO_DIR/php/protected/runtime

if [ ! -d $OPENSHIFT_DATA_DIR/assets ]; then
    mkdir $OPENSHIFT_DATA_DIR/assets
fi

ln -sf $OPENSHIFT_DATA_DIR/assets $OPENSHIFT_REPO_DIR/php/assets
